config/routes.rb
Rails.application.routes.draw do
  root 'home_page#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes
  end

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  resources :recipes

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/home.html.erb
<!-- Half Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/assets/img4.jpg');"></div>
            <div class="carousel-caption">
                <h2>Caption 1</h2>
            </div>
        </div>
        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('/assets/img3.png');"></div>
            <div class="carousel-caption">
                <h2>Caption 2</h2>
            </div>
        </div>
        <div class="item">
            <!-- Set the third background image using inline CSS below. -->
            <div class="fill" style="background-image:url('http://lorempixel.com/750/500/food');"></div>
            <div class="carousel-caption">
                <h2>Caption 3</h2>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>

<div class="">
    <div class="">
      <h1>Recipe's App Home Page</h1>

      <%= link_to signup_path, class: "btn btn-success btn-lg" do %>
        Sign Up <span class="glyphicon glyphicon-cutlery"></span>
      <% end %>
    </div><br>

    <p class="lead">
        <%= link_to "View Recipes", recipes_path %>
    </p>
</div>

<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
   interval: 5000 //changes the speed
})
</script>