config/routes.rb
Rails.application.routes.draw do
  root 'home_page#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes
  end

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :instructions, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user

  has_many :pantries
  has_many :ingredients, through: :pantries, dependent: :destroy

  has_many :recipe_categories
  has_many :categories, through: :recipe_categories, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true
  validates :description, presence: true

  scope :recent, -> (limit) { order('created_at DESC').limit(limit) }

  def self.recent
    order("created_at DESC").limit(limit)
  end

  # accepts_nested_attributes_for :instructions
  # accepts_nested_attributes_for :ingredients
  # accepts_nested_attributes_for :categories

  # def categories_attributes=(category_attributes)
  #   category_attributes.values.each do |category_attribute|
  #     category = Category.find_or_create_by(category_attribute)
  #     self.categories << category
  #   end
  # end

  # def instructions_attributes=(instruction_attributes)
  #   instruction_attributes.each do |i, instruction_attribute|
  #     if instruction_attribute[:content].present?
  #       instruction = Instruction.find_or_create_by(content: instruction_attribute[:content])
  #       if !self.instructions.include?(instruction)
  #         self.recipe_instructions.build(:instruction => instruction)
  #       end
  #     end
  #   end
  # end

  # def ingredients_attributes=(ingredient_attributes)
  #   ingredient_attributes.each do |i, attribute|
  #     if (!(attribute.values.any? &:blank?))
  #       ingredient = Ingredient.find_or_create_by(name: attribute['name'])
  #       self.recipe_ingredients.build(ingredient_id: ingredient.id, name: attribute['name'])
  #     end
  #   end
  # end

  def instructions_attributes=(instruction_attributes)
    instruction_attributes.values.each do |instruction_attribute|
      if instruction_attribute[:content].present?
        instruction = Instruction.find_or_create_by(instruction_attribute)
        self.instructions << instruction
      end
    end
  end

  def ingredients_attributes=(ingredient_attributes)
		ingredient_attributes.values.each do |ingredient_attribute|
			if ingredient_attribute[:name].length > 0
				ingredient = Ingredient.find_or_create_by(ingredient_attribute)
				self.ingredients << ingredient
			end
		end
	end

  def categories_attributes=(category_attributes)
      # {"0"=>{"name"=>"Lunch"}, "1"=>{"name"=>"Dinner"}}
      # create a category for each of the hashes inside category_attributes
      category_attributes.each do |i, category_attribute|
        # create a new category if this recipe doesn't already have this category
        # find or create the category regardless of whether this recipe has it...

        # don't create a category if it doesn't have name
        if category_attribute[:name].present?
          # But also don't add a category to a recipe if it already has it.
          # how do I check if this recipe has this category already?

          category = Category.find_or_create_by(name: category_attribute[:name])
          if !self.categories.include?(category)
            # why is this ineffecient and not ideal?
            # self.categories << category
            self.recipe_categories.build(:category => category)
            # I need to create a category that is already associated with this recipe
            # and I need to make sure that this category already doesn't exist by name.
          end
        end
      end
    end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    if params[:user_id] && !User.exists?(params[:user_id])
      flash[:danger] = "User not found!"
      redirect_to users_path
    else
      @recipe = Recipe.new(user_id: params[:user_id])
      3.times do
        @recipe.ingredients.build
      end
      3.times do
        @recipe.instructions.build
      end
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to user_recipe_path(@recipe.user, @recipe)
    else
      render :new
    end
  end

  def edit
    if params[:user_id]
      user = User.find_by(id: params[:user_id])
      if user.nil?
        flash[:danger] = "User not found!"
        redirect_to to users_path
      else
        @recipe = user.recipes.find_by(id: params[:id])
        redirect_to user_recipes_path(user), alert: "Recipe not found!" if @recipe.nil?
      end
    end
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:success] = "Recipe updated!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:danger] = "Recipe deleted!"
    redirect_to user_recipes_path(@recipe.user)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :user_id, instructions_attributes: [:content], ingredient_ids: [], ingredients_attributes: [:name], category_ids: [], categories_attributes: [:name])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def user_id_field(recipe)
    if recipe.user.nil?
      select_tag "recipe[user_id]", options_from_collection_for_select(User.all, :id, :name)
    else
      hidden_field_tag "recipe[user_id]", recipe.user_id
    end
  end
end

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @recipe do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows:"3" %>
      <p><%= user_id_field(@recipe) %></p>

      <h3><strong>Instructions</strong></h3>

      <%= f.fields_for :instructions do |inst| %>
        <%= inst.text_area :content, class: "form-control", rows:"3" %>
      <% end %>

      <h3><strong>Categories</strong></h3>

      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
      <%= f.fields_for :categories, @recipe.categories.build do |categories_fields| %>
        <p>New Categoy: <%= categories_fields.text_field :name, class: "form-control" %></p>
      <% end %>

      <h3><strong>Ingredients</strong></h3>

      <!-- <%= f.fields_for :ingredients do |i| %>
          <%= i.text_field :name, class: "form-control" %>
      <% end %> -->


    	<%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %><br>

      <h4><strong>Custom Ingredients</strong></h4>

    	<!-- <h4><%= f.label "Custom Ingredients" %></h4> -->
    	<%= f.fields_for :ingredients do |i| %>
    		<%= i.text_field :name, class: "form-control" %>
    	<% end %>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="col-lg-8">
  <h1><strong>Edit Recipe</strong></h1>

  <%= render 'form' %>

</div><br>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/recipes/index.html.erb
<!-- Recipe Entries Column -->
<div class="col-md-8">

    <h1 class="page-header">
        All Recipes
    </h1>

    <!-- First Recipe Post -->
    <% current_user.recipes.each do |recipe| %>
      <h2>
          <!-- <%= link_to recipe.name, recipe_path(recipe) %> -->
          <%= link_to recipe.name, user_recipe_path(recipe.user, recipe) if recipe.user %>
      </h2>
      <p class="lead">
          by <%= recipe.user.name if recipe.user %>
      </p>
      <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(recipe.created_at) %> ago</p>
      <hr>
      <img class="img-responsive" src="http://lorempixel.com/900/300/food" alt="">
      <hr>
      <p><%= recipe.description %></p>
      <%= link_to user_recipe_path(recipe.user, recipe), class: "btn btn-primary" do %>
        Read More<span class="glyphicon glyphicon-chevron-right"></span>
      <% end %>

      <hr>
    <% end %>

    <!-- Pager -->
    <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Older</a>
        </li>
        <li class="next">
            <a href="#">Newer &rarr;</a>
        </li>
    </ul>

</div><!-- End Recipe Entries Column -->

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/recipes/new.html.erb
<div class="col-lg-8">
  <h1><strong>New Recipe</strong></h1>

  <%= render 'form' %>

</div><br>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/recipes/show.html.erb
<!-- Recipe Post Content Column -->
<div class="col-lg-8">
  <%= link_to recipes_path, class: "btn btn-info" do %>
    <span class="glyphicon glyphicon-menu-left"></span>
  <% end %>
    <!-- Recipe Post -->

    <!-- Title -->
    <h1>
      <%= @recipe.name %>
      <small><%= link_to new_user_recipe_path(@recipe.user), class: "btn btn-success" do %>
        New Recipe <span class="glyphicon glyphicon-plus"></span>
      <% end %>
      </small>
      <small><%= link_to edit_user_recipe_path(@recipe.user, @recipe), class: "btn btn-warning" do %>
        Edit Recipe <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      </small>
      <small>
        <%= link_to recipe_path(@recipe), method: :delete, class: "btn btn-danger btn",	data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </small>
    </h1>

    <!-- Author -->
    <p class="lead">
        by <%= link_to @recipe.user.name, user_recipes_path(@recipe.user) if @recipe.user %>
    </p>

    <strong>Categories</strong>
    <% @recipe.categories.each do |category| %>
      <small><%= category.name %></small>
    <% end %>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted <%= time_ago_in_words(@recipe.created_at) %> ago</p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="http://lorempixel.com/900/300/food" alt="">

    <hr>

    <!-- Recipe Content -->
    <!-- Description -->
    <p class="lead"><strong>Description</strong> - <i><%= @recipe.description %></i></p>

    <!-- Instructions -->
    <p class="lead"><strong>Instructions</strong></p>
    <% @recipe.instructions.each do |instruction| %>
      <p><%= instruction.content %></p>
    <% end %>

    <p class="lead"><strong>Ingredients</strong></p>
    <% @recipe.ingredients.each do |ingredient| %>
      <p><%= ingredient.name %></p>
    <% end %>
    <hr>

    <!-- Recipe Review -->

    <!-- Comments Form -->
    <div class="well">
      <h4>Leave a Review:</h4>
      <%= form_for([@recipe, @recipe.reviews.build]) do |f| %>
        <div class="form-group">
          <%= f.hidden_field :user_id %>
          <!-- <%= f.hidden_field :recipe_id %> -->
          <!-- <%= f.label :content %> -->
          <%= f.text_area :content, class: "form-control", row: "3" %>
          <p>Select user: <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :name) %></p>
        </div>
        <%= f.submit "Create Review", class: "btn btn-primary" %>
      <% end %>
    </div>

    <hr>

    <!-- Posted Reviews -->
    <!-- find how to add 'recipe_id' to the reviews below,  because its returning 'nil' -->

    <!-- Review -->
    <% @recipe.reviews.each do |review| %>
    <div class="media">
      <a class="pull-left" href="#">
        <img class="media-object" src="http://lorempixel.com/64/64/people" alt="">
      </a>
      <div class="media-body">
        <h4 class="media-heading"><%= review.user_id %>
          <small>August 25, 2014 at 9:30 PM</small>
          <%= link_to [review.recipe, review], method: :delete, class: "btn btn-danger btn-xs",	data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </h4>
        <%= review.content %>
      </div>
    </div>
    <% end %>
    <br>

</div><!-- End Recipe Post Content Column -->

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>