config/routes.rb
Rails.application.routes.draw do
  root 'home_page#home'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    resources :recipes
  end

  resources :recipes do
    resources :reviews, only: [:create, :destroy]
  end

  resources :recipes

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }

  private

  # Convert email to all lower-case
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Recipe App!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted!"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters

  # Confirms the correct user
  def correct_user
    @user = User.find(params[:id])
    if !current_user?(@user)
      flash[:danger] = "You don't have permission to access this page!"
    end
    redirect_to(root_path) unless current_user?(@user)
  end

  # Confirms an admin user
  def admin_user
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-lg-8">
  <h1>Edit User</h1>

  <%= render 'form' %>
  
</div><br>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/users/index.html.erb
<div class="col-lg-8">
  <h1>All Users</h1>

  <!-- Left-aligned media object -->
  <% @users.each do |user| %>
    <div class="media">
      <div class="media-left">
        <!-- <%= image_tag("img1.png") %> -->
        <img class="media-object" src="http://lorempixel.com/64/64/people" alt="">
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to user.name, user_path(user) %></h4>
        <% if current_user.admin? && !current_user?(user) %><small><%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %></small>
        <% end %>
      </div>
      <hr>
    </div>
  <% end %>
</div>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/users/new.html.erb
<div class="col-lg-8">
  <h1>New User</h1>

  <%= render 'form' %>

</div><br>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>

app/views/users/show.html.erb
<div class="col-lg-8">
  <!-- User Entries Column -->
  <div class="col-md-8">

      <!-- Portfolio Item Heading -->
      <div class="row">
          <div class="col-lg-12">
              <h1 class="page-header"><%= @user.name %>'s Profile
                  <small>
                  <%= link_to new_user_recipe_path(@user), class: "btn btn-success" do %>
                    New Recipe <span class="glyphicon glyphicon-plus"></span>
                  <% end %>
                  </small>
              </h1>
          </div>
      </div> <!-- /.row -->

      <!-- Portfolio Item Row -->
      <div class="row">

          <div class="col-md-8">
              <img class="img-responsive" src="http://lorempixel.com/750/500/people" alt="">
          </div>

          <div class="col-md-4">
            <h3>Biography</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
          </div>

      </div><!-- /.row -->

      <!-- Related Projects Row -->
      <div class="row">

          <div class="col-lg-12">
              <h3 class="page-header">Related Recipes</h3>
          </div>

          <% current_user.recipes.each do |recipe|  %>
          <div class="col-sm-3 col-xs-6 hero-feature">
            <div class="thumbnail text-center">
              <a href="#">
                  <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/food" alt="">
              </a>
                <h4>
                    <%= link_to recipe.name, user_recipe_path(current_user, recipe) %>
                </h4>
            </div>
          </div>
          <% end %>

      </div><!-- /.row -->

  </div><!-- End User Entries Column -->
</div><br>

<!-- Sidebar moved to partial -->
<%= render 'layouts/sidebar' %>